frameworkVersion: '=1.5.1'

plugins:
  - serverless-webpack

service: yith

custom:
  registry: 'https://registry.npmjs.org/'
  github: 'https://api.github.com/'
  bucket: 'npm-registry'
  cache: false

provider:
  name: aws
  region: eu-central-1
  runtime: nodejs4.3
  stage: dev
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
        - "s3:GetObject"
        - "s3:PutObject"
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
        - "apigateway:POST"
      Resource:
        - "arn:aws:s3:::${self:custom.bucket}-${opt:stage}*"
        - "arn:aws:apigateway:*"

functions:
  get:
    handler: get.default
    environment:
      region: ${self:provider.region}
      bucket: ${self:custom.bucket}-${opt:stage}
      registry: ${self:custom.registry}
    events:
      - http:
          path: 'registry/{name}'
          method: get
          integration: lambda

  distTagsGet:
    handler: distTagsGet.default
    environment:
      region: ${self:provider.region}
      bucket: ${self:custom.bucket}-${opt:stage}
      registry: ${self:custom.registry}
    events:
      - http:
          path: 'registry/-/package/{name}/dist-tags'
          method: get
          integration: lambda

resources:
  Resources:
    PackageStorage:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: Private
        BucketName: ${self:custom.bucket}-${opt:stage}
