frameworkVersion: '=1.5.1'

plugins:
  - serverless-webpack

service: yith

provider:
  name: aws
  region: eu-central-1
  runtime: nodejs4.3
  stage: dev
  environment:
    registry: ${env:YITH_REGISTRY}
    githubUrl: ${env:YITH_GITHUB_URL}
    githubClientId:  ${env:YITH_GITHUB_CLIENT_ID}
    githubSecret:  ${env:YITH_GITHUB_SECRET}
    bucket: ${env:YITH_BUCKET}-${opt:stage}
    region: ${self:provider.region}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
        - "s3:GetObject"
        - "s3:PutObject"
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
        - "apigateway:POST"
      Resource:
        - "arn:aws:s3:::${self:provider.environment.bucket}*"
        - "arn:aws:apigateway:*"

functions:
  get:
    handler: get.default
    events:
      - http:
          path: 'registry/{name}'
          method: get

  distTagsGet:
    handler: distTagsGet.default
    events:
      - http:
          path: 'registry/-/package/{name}/dist-tags'
          method: get
  distTagsPut:
    handler: distTagsPut.default
    events:
      - http:
          path: 'registry/-/package/{name}/dist-tags/{tag}'
          method: put
  distTagsDelete:
    handler: distTagsDelete.default
    events:
      - http:
          path: 'registry/-/package/{name}/dist-tags/{tag}'
          method: delete

resources:
  Resources:
    PackageStorage:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: Private
        BucketName: ${self:provider.environment.bucket}
